services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks: [mqtt-net]

  falcon-strike-command:
    image: maven:3.9.10-eclipse-temurin-24
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: "1883"
      LOG4J_CONFIGURATION_FILE: /config/log4j2.xml
    build:
      context: ./falcon-strike-command
      dockerfile: Dockerfile
    container_name: falcon-strike-command
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
    volumes:
      - ./shared/log4j2.xml:/config/log4j2.xml:ro
      - ./falcon-strike-command:/app
      - ./shared/entrypoint.sh:/entrypoint.sh:ro
      - ./shared/proto:/proto:ro
    ports:
      - "8081:8080"
    networks: [mqtt-net]

  eagle-eye-broadcast:
    image: maven:3.9.10-eclipse-temurin-24
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: "1883"
      LOG4J_CONFIGURATION_FILE: /config/log4j2.xml
    build:
      context: ./eagle-eye-broadcast
      dockerfile: Dockerfile
    container_name: eagle-eye-broadcast
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
    volumes:
      - ./shared/log4j2.xml:/config/log4j2.xml:ro
      - ./eagle-eye-broadcast:/app
      - ./shared/entrypoint.sh:/entrypoint.sh:ro
      - ./shared/proto:/proto:ro
    ports:
      - "8082:8080"
    networks: [mqtt-net]

  hawk-engagement-monitor:
    image: maven:3.9.10-eclipse-temurin-24
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: "1883"
      LOG4J_CONFIGURATION_FILE: /config/log4j2.xml
    build:
      context: ./hawk-engagement-monitor
      dockerfile: Dockerfile
    container_name: hawk-engagement-monitor
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
    volumes:
      - ./shared/log4j2.xml:/config/log4j2.xml:ro
      - ./hawk-engagement-monitor:/app
      - ./shared/entrypoint.sh:/entrypoint.sh:ro
      - ./shared/proto:/proto:ro
    ports:
      - "8083:8080"
    networks: [mqtt-net]

  viper-listener:
    image: maven:3.9.10-eclipse-temurin-24
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: "1883"
      LOG4J_CONFIGURATION_FILE: /config/log4j2.xml
    build:
      context: ./viper-listener
      dockerfile: Dockerfile
    container_name: viper-listener
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
    volumes:
      - ./shared/log4j2.xml:/config/log4j2.xml:ro
      - ./viper-listener:/app
      - ./shared/entrypoint.sh:/entrypoint.sh:ro
      - ./shared/proto:/proto:ro
    ports:
      - "8084:8080"
    networks: [mqtt-net]

  raptor-listener:
    image: maven:3.9.10-eclipse-temurin-24
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: "1883"
      LOG4J_CONFIGURATION_FILE: /config/log4j2.xml
    build:
      context: ./raptor-listener
      dockerfile: Dockerfile
    container_name: raptor-listener
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
    volumes:
      - ./shared/log4j2.xml:/config/log4j2.xml:ro
      - ./raptor-listener:/app
      - ./shared/entrypoint.sh:/entrypoint.sh:ro
      - ./shared/proto:/proto:ro
    ports:
      - "8085:8080"
    networks: [mqtt-net]

  hydra-duplex-node:
    image: maven:3.9.10-eclipse-temurin-24
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: "1883"
      LOG4J_CONFIGURATION_FILE: /config/log4j2.xml
    build:
      context: ./hydra-duplex-node
      dockerfile: Dockerfile
    container_name: hydra-duplex-node
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
    volumes:
      - ./shared/log4j2.xml:/config/log4j2.xml:ro
      - ./hydra-duplex-node:/app
      - ./shared/entrypoint.sh:/entrypoint.sh:ro
      - ./shared/proto:/proto:ro
    ports:
      - "8086:8080"
    networks: [mqtt-net]
networks:
  mqtt-net:
    driver: bridge
